export const TEST_SPECIFICATION_REGISTRY = {
  ZOD: {
    EMAIL: {
      MOCK: Symbol.for("MODULE:APPLICATION:SPECIFICATION:ZOD:EMAIL:MOCK"),
      SIMULATE: Symbol.for(
        "MODULE:APPLICATION:SPECIFICATION:ZOD:EMAIL:SIMULATE",
      ),
    },
    INVOICE: {
      MOCK: Symbol.for("MODULE:APPLICATION:SPECIFICATION:ZOD:INVOICE:MOCK"),
      SIMULATE: Symbol.for(
        "MODULE:APPLICATION:SPECIFICATION:ZOD:INVOICE:SIMULATE",
      ),
    },
  },
};
