export const TEST_HTTP_SERVER_REGISTRY = {
  HTTP: {
    EXPRESS: {
      MOCK: Symbol.for("MOCK::MODULE:INFRA:SERVER:HTTP:EXPRESS"),
      SIMULATE: Symbol.for("SIMULATE::MODULE:INFRA:SERVER:HTTP:EXPRESS"),
    },
  },
};
