FROM postgres:15-alpine

COPY migration/versions /migrations
COPY migration/runner.sh /usr/local/bin/run-migrations

RUN chmod 0555 /usr/local/bin/run-migrations

USER postgres

ENTRYPOINT ["/usr/local/bin/run-migrations"]
