export const TEST_SERVICE_REGISTRY = {
  EMAIL: {
    MOCK: Symbol.for("MODULE:APPLICATION:SERVICE:EMAIL:MOCK"),
    SIMULATE: Symbol.for("MODULE:APPLICATION:SERVICE:EMAIL:SIMULATE"),
  },
  INVOICE: {
    MOCK: Symbol.for("MODULE:APPLICATION:SERVICE:INVOICE:MOCK"),
    SIMULATE: Symbol.for("MODULE:APPLICATION:SERVICE:INVOICE:SIMULATE"),
  },
};
