export const TEST_CONTROLLER_REGISTRY = {
  INVOICE: {
    MOCK: Symbol.for("MODULE:APPLICATION:CONTROLLER:INVOICE:MOCK"),
    SIMULATE: Symbol.for("MODULE:APPLICATION:CONTROLLER:INVOICE:SIMULATE"),
  },
  EMAIL: {
    MOCK: Symbol.for("MODULE:APPLICATION:CONTROLLER:EMAIL:MOCK"),
    SIMULATE: Symbol.for("MODULE:APPLICATION:CONTROLLER:EMAIL:SIMULATE"),
  },
};
