export const HTTP_SERVER_ENGINE_REGISTRY = {
  EXPRESS: {
    _: "HTTP_REGISTRY.EXPRESS.SERVER",
    PARSER: {
      JSON: "HTTP_REGISTRY.EXPRESS.PARSER.JSON",
    },
    CORS: "HTTP_REGISTRY.EXPRESS.CORS",
  },
};
