export const TEST_REPOSITORY_REGISTRY = {
  SQL: {
    CONTRACT: {
      MOCK: Symbol.for("MODULE:INFRA:REPOSITORY:SQL:CONTRACT:MOCK"),
      SIMULATE: Symbol.for("MODULE:INFRA:REPOSITORY:SQL:CONTRACT:SIMULATE"),
    },
    PAYMENT: {
      MOCK: Symbol.for("MODULE:INFRA:REPOSITORY:SQL:PAYMENT:MOCK"),
      SIMULATE: Symbol.for("MODULE:INFRA:REPOSITORY:SQL:PAYMENT:SIMULATE"),
    },
  },
};
